### ISSUE TITLE
Feature request: Click / Double click on tray icon to toggle

### ISSUE THREAD

**Issue by davidsedlar** [ankurk91/google-chat-electron#37]
Love the Windows build, using it daily. But I would love if you you could click/ double click on the try icon to toggle main window (show or hide), instead of having to right click -> Toggle. Much like Slack and similar apps.

Thanks!

**Comment by ankurk91** [comment]
If this feature available natively in electron, i will implement it soon.

**Comment by ankurk91** [comment]
fixed in 2.10.0, let me know if does not work for you.

**Comment by davidsedlar** [comment]
> fixed in 2.10.0, let me know if does not work for you.

Thanks. Works perfectly on Windows 10. 👍

**Comment by erik2282** [comment]
Still the same on Ubuntu 21.04 with Gnome 3.38.5 after updating to latest google-chat-electron.

**Comment by ankurk91** [comment]
It is not possible to add click on tray icon on linux.
This is a limitation in electroniitself

**Comment by erik2282** [comment]
ok thanks.
